import React from 'react';
import BookCard from '../components/BookCard';
import img1 from '../assets/image1.png';
import img2 from '../assets/image2.png';
import img3 from '../assets/image3.png';  

const SampleBooks = () => {
    const books = [
        {
            image: img1,
            title: 'The Quantum Paradox',
            genre: 'Science Fiction',
            description: 'As Dr. Elara stepped through the shimmering portal, she knew there was no turning back. The fate of two universes now rested in her hands...'
        },
        {
            image: img2,
            title: 'Whispers in the Mist',
            genre: 'Mystery',
            description: 'The old lighthouse stood silent, its beacon long extinguished. But on foggy nights, some swore they could still see its ghostly light...'
        },
        {
            image: img3,
            title: 'Echoes of Eternity',
            genre: 'Fantasy',
            description: 'The ancient prophecy spoke of a child born with starlight in their eyes. As the comet blazed overhead, the kingdom held its breath...'
        }
    ];

    return (
        <div 
            className="p-12 w-10/12 mx-auto"
        >
            <h2 className="text-center text-3xl font-bold mb-6">Sample Books Generated by BookAI</h2>
            <p className="text-center text-xl text-[#d4d4d4] mb-12">Explore some of the captivating books created using our AI technology.</p>
            <div className="grid grid-cols-1 md:grid-cols-2 p-1 items-center gap-y-6 lg:grid-cols-3 justify-center space-x-6">
                {books.map((book, index) => (
                    <BookCard
                        key={index}
                        image={book.image}
                        title={book.title}
                        genre={book.genre}
                        description={book.description}
                    />
                ))}
            </div>
        </div>
    );
}

export default SampleBooks;
